name: StaffModePlusPlus
version: 0.9.4
main: io.github.itskev.staffmodepp.StaffModePP
author: ItsKev
softdepend: [PlaceholderAPI]
depend: [ProtocolLib]

commands:
  staffmode:
    description: Put the player in staff mode
  vanish:
    description: Put the player in vanished mode
  noclip:
    description: Put the player in noclip mode
  freeze:
    description: Freeze a player
    usage: /freeze %Player%
  unfreeze:
    description: Unfreeze a player
    usage: /unfreeze %Player%
  follow:
    description: Follow a player
    usage: /follow %Player%
  cps:
    description: Check clicks per second from player
    usage: /cps %Player% %Duration%
  staffonline:
    description: Get staff players online
    usage: /staffonline
  rtpm:
    description: Get all miners