name: StaffModePlusPlus
version: 0.3
main: io.github.itskev.staffmodepp.StaffModePP

commands:
  staffmode:
    description: Put the player in staff mode
  vanish:
    description: Put the player in vanished mode
  noclip:
    description: Put the player in noclip mode
  freeze:
    description: Freeze a player
    usage: /freeze %Player%
  unfreeze:
    description: Unfreeze a player
    usage: /unfreeze %Player%
  follow:
    description: Follow a player
    usage: /follow %Player%