name: StaffModePlusPlus
version: 0.2
main: io.github.itskev.staffmodepp.StaffModePP

commands:
  staffmode:
    description: Put the player in staff mode
  vanish:
    description: Put the player in vanished mode